package org.arpanm18.exercise.dto;

public enum Action {
    PURCHASE_PHYSICAL_PRODUCT,
    GENERATE_PACKING_SLIP,
    PURCHASE_BOOK,
    ACTIVATE_MEMBERSHIP, UPGRADE_MEMBERSHIP, GENERATE_DUPLICATE_PACKING_SLIP
}
