package org.arpanm18.exercise.dto;

public enum Action {
    PURCHASE_PHYSICAL_PRODUCT,
    GENERATE_PACKING_SLIP,
    PURCHASE_BOOK,
    ACTIVATE_MEMBERSHIP, UPGRADE_MEMBERSHIP, SEND_EMAIL_NOTIFICATIONS, LEARN_TO_SKI_VIDEO, FIRST_AID_VIDEO, GENERATE_DUPLICATE_PACKING_SLIP
}
